services:
  db:
    image: postgres
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    networks: 
      - webnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patients
    ports:
      - "5432:5432"

networks:
  webnet: